on:
  push:
    branches: [master]

name: Generate Github Release
jobs:
  get-spec-version:
    name: Get OpenAPI document version from version.txt
    runs-on: ubuntu-latest
    outputs:
      spec-version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: get-version
        run: echo "::set-output name=version::$(cat version.txt)"


  release-please:
    needs: get-spec-version
    runs-on: ubuntu-latest
    # outputs:
    #   did-create-release: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: circle-openapi
          version-file: VERSION
          release-as: ${{ needs.get-spec-version.outputs.spec-version }}